### ISSUE TITLE
Aligning with layout guide

### ISSUE THREAD

**Issue by mstfy** [Masonry/Snappy#13]
How a view can be aligned to self.topLayoutGuide or bottomLayoutGuide?

**Comment by robertjpayne** [comment]
This is now done in develop! Enjoy.

**Comment by ndbroadbent** [comment]
Hi @robertjpayne, I just tried this out, and it compiles, but there are no `snp_*` methods on the layout guides. So I am unable to set the top of my view to the bottom of the layout guide, I can only set it to the top (which is the top of the window). Would it be possible to add the `snp_top`, `snp_bottom`, etc. method to `UILayoutSupport`?
