### ISSUE TITLE
Add support for updateConstraints to match Masonry functionality.

### ISSUE THREAD

**Issue by cnoon** [Masonry/Snappy#14]
In Masonry, we have the option to `makeConstraints`, `remakeConstraints`, and `updateConstraints`. In Snappy, we can no longer `updateConstraints`. It would be nice to still have this functionality.

**Comment by robertjpayne** [comment]
@cnoon you can grab it in develop now. And to anyone else it's ready to go granted I've not tested it extensively so any help there is greatly appreciated.

Let me know how the performance is, it has the same logic as Masonry so it should perform similarly but it could definitely be improved.

**Comment by cnoon** [comment]
This is great @robertjpayne! We'll definitely give it some extensive testing over the next few weeks. On another note, thanks for all the activity and updates in the last week. We absolutely love using Snappy and really appreciate all your awesome work!
