### ISSUE TITLE
Xcode warning 'embedded dylibs/frameworks only run on iOS 8 or later'

### ISSUE THREAD

**Issue by ryanmaxwell** [Masonry/Snappy#32]
Can we bump the framework deployment target from 7.0 to 8.0 to get rid of this annoying warning in Xcode? If you're using Snappy in iOS7, you're likely just using the source files directly rather than the embedded framework target in the app?
![screen shot 2014-12-09 at 17 26 02](https://cloud.githubusercontent.com/assets/718440/5352340/f95e7982-7fc8-11e4-939b-5fd8c0829778.png)

**Comment by robertjpayne** [comment]
Done in develop.
