### ISSUE TITLE
Time to support cocoapods?

### ISSUE THREAD

**Issue by favoyang** [Masonry/Snappy#33]
Since CocoaPods 0.36.0.beta.1, it's possible to make a swift framework - http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by robertjpayne** [comment]
@devxoul @favoyang it's ready to go! If you have Cocoapods up to date you can install it. Currently `Snappy` is already taken in Cocoapods so for the time being you have to target the Git repository directly.
